version: "2.2"
services:
  redis-cache:
    container_name: app-redis
    image: redis:alpine
    environment:
      - SERVER_PORT=6379
    restart: unless-stopped
    mem_limit: 128m
    # 1024 - default
    cpu_shares: 1024
    healthcheck:
      test: [ "CMD-SHELL", "echo INFO | nc localhost 6379" ]
      interval: 30s
      timeout: 10s
      retries: 5
  postgres:
    container_name: app-postgres
    image: postgres
    environment:
      - SERVER_PORT=5432
      - TZ=UTC
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=test
    restart: unless-stopped
    mem_limit: 256m
    cpu_shares: 1024
    healthcheck:
      test: [ "CMD-SHELL", "sh -i -c pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    container_name: app
    image: spring-boot2-template
    environment:
      - TZ=UTC
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgres:5432/test
      - DB_USER=user
      - DB_PASSWORD=123
      - REAL_CONTEXT_PATH=/
      - JAVA_OPTS=-Xmx256m -Duser.timezone=UTC -Dfile.encoding=UTF-8
      - JAVA_BINARY=/usr/bin/java-app
      - WAITFOR=postgres:5432 -t 60
      - SERVER_PORT=8087
    restart: unless-stopped
    mem_limit: 512m
    memswap_limit: 1g
    cpu_shares: 512
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8087/management/health" ]
      interval: 1m
      timeout: 1m
      retries: 5
