version: 2

jobs:
  # Build Website
  doc:
    working_directory: ~/docs
    docker:
    - image: circleci/openjdk:8-node-browsers
    steps:
    - checkout
    - run:
      - git config --global user.email "circleci@fabric8.io"
      - git config --global user.name "CircleCI"
    - run: bash ./mkdocs.sh
    - save_cache:
        key: docs-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

workflows:
  version: 2
  all:
    jobs:
    - doc:
        filters:
          branches:
            only: master

